// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuulfgekzffpwdxkwwzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dWxmZ2VremZmcHdkeGt3d3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Nzk2NjgsImV4cCI6MjA3NDU1NTY2OH0.U7En8uut6OIadTYftO7EMpxqQleF8YSXRK2ZmHEaBnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});